[wokwi]
version = 1
# Exercise
firmware = "target/riscv32imc-esp-espidf/debug/examples/solution"
elf = 'target/riscv32imc-esp-espidf/debug/button-interrupt'

# Solution
# firmware = 'target/riscv32imc-esp-espidf/debug/examples/solution'
# elf = 'target/riscv32imc-esp-espidf/debug/examples/solution'

# Solution - LED
# firmware = 'target/riscv32imc-esp-espidf/debug/examples/solution_led'
# elf = 'target/riscv32imc-esp-espidf/debug/examples/solution_led'
